### ISSUE TITLE
[scss] gap of text

### ISSUE THREAD

**Issue by Shenglian** [Shenglian/WORK_TIP#10]
```scss
// 文字上下間距一樣
@mixin textHeightCenter($height){
  height: $height;
  line-height: $height;    
} 
```
