### ISSUE TITLE
[scss] center of text

### ISSUE THREAD

**Issue by Shenglian** [Shenglian/WORK_TIP#11]
```scss
// 文字置中
@mixin textCenter($height){
  height: $height;
  line-height: $height;    
  text-align: center;
} 
```
