### ISSUE TITLE
[scss] ellipsis

### ISSUE THREAD

**Issue by Shenglian** [Shenglian/WORK_TIP#12]
```scss
// 多餘文字變成....
%omitted-words {
  overflow : hidden;
  text-overflow : ellipsis;
  white-space : nowrap;
}

@mixin omitted-words {
  @extend %omitted-words;
}
```
