### ISSUE TITLE
[scss]

### ISSUE THREAD

**Issue by Shenglian** [Shenglian/WORK_TIP#13]
```scss
$z-layers: (
	"sidebar": 10000,
	"sidebar-overlay": 9999
);

// 針對 Cupoy Moblie 的 Z index 做設定
@function z($zindex) {
	@if not map-has-key($z-layers, $zindex){
		@warn "No z-index found for '#{$zindex}' in z-layers map!"
	}
	@return map-get($z-layers,  $zindex);
}
```
