### ISSUE TITLE
[scss] Css Responsive Square and Rectangle

### ISSUE THREAD

**Issue by Shenglian** [Shenglian/WORK_TIP#15]
```scss
// Css Responsive Square and Rectangle
@mixin square($size, $scale){
	position: relative;
	width: $size + %;  				/* desired width */
	&:before {
		content: "";
		display: block;
		padding-top: $scale + %;        /* initial ratio */
	}
}
```
