### ISSUE TITLE
[css] hide scrollBar 

### ISSUE THREAD

**Issue by Shenglian** [Shenglian/WORK_TIP#16]
```css
//方式一
#parent{
    height: 100%;
    width: 100%;
    overflow: hidden;
}

#child{
    width: 100%;
    height: 100%;
    overflow: auto;
    padding-right: 15px; /* Increase this value for cross-browser compatibility */
}

//方式二，Using Position: absolute

#parent{
    height: 100%;
    width: 100%;
    overflow: hidden;
    position: relative;
}

#child{
    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    right: -15px; /* Decrease this value for cross-browser compatibility */
    overflow: auto;
}
```
