### ISSUE TITLE
[css] 最後一行，顯示點點點點。（標準太新不能用）

### ISSUE THREAD

**Issue by Shenglian** [Shenglian/WORK_TIP#18]
```css
.article {  
  /*width: 200px;*/
  color: #000000;
  overflow: hidden;
  display: -webkit-box;
  -webkit-line-clamp: 3;
  -webkit-box-orient: vertical;
  word-break: break-all;  
} 
```
