### ISSUE TITLE
[css] intrinsic rario

### ISSUE THREAD

**Issue by Shenglian** [Shenglian/WORK_TIP#30]
```html
<div class="embed-responsive embed-responsive-16by9">
  <video src="https://www.w3schools.com/html/mov_bbb.mp4"></video>
</div>
```
```css
.embed-responsive {
  position: relative;
  display: block;
  height: 0;
  padding: 0;
  overflow: hidden;
}

.embed-responsive .embed-responsive-item,
.embed-responsive iframe,
.embed-responsive embed,
.embed-responsive object,
.embed-responsive video {
  position: absolute;
  top: 0;
  bottom: 0;
  left: 0;
  width: 100%;
  height: 100%;
  border: 0;
}

.embed-responsive-16by9 {
  padding-bottom: 56.25%;
}

.embed-responsive-4by3 {
  padding-bottom: 75%;
}
```
