### ISSUE TITLE
[小程式] 製作 input range

### ISSUE THREAD

**Issue by Shenglian** [Shenglian/WORK_TIP#34]
```html
<div>50</div>
<input type="range" />
<button id="increase">increase button</button>
<button id="decrease">decrease button</button>
```
```css
input[type=range]{
  -webkit-appearance: none;
  background: none;
}

input[type=range]::-webkit-slider-runnable-track {
  height: 5px;
  background: #ddd;
  border: none;
  border-radius: 3px;
}

input[type=range]::-ms-track {
  height: 5px;
  background: #ddd;
  border: none;
  border-radius: 3px;
}

input[type=range]::-moz-range-track {
  height: 5px;
  background: #ddd;
  border: none;
  border-radius: 3px;
}

input[type=range]::-webkit-slider-thumb {
  -webkit-appearance: none;
  border: none;
  height: 16px;
  width: 16px;
  border-radius: 50%;
  background: #555;
  margin-top: -5px;
  position: relative;
}

input[type=range]::-ms-thumb {
  -webkit-appearance: none;
  border: none;
  height: 16px;
  width: 16px;
  border-radius: 50%;
  background: #555;
  margin-top: -5px;
  position: relative;
}

input[type=range]::-moz-range-thumb {
  -webkit-appearance: none;
  border: none;
  height: 16px;
  width: 16px;
  border-radius: 50%;
  background: #555;
  margin-top: -5px;
  position: relative;
}

input[type=range]:focus {
  outline: none;
  &::-webkit-slider-thumb:after {
    position: absolute;
    top: -35px;
    left: 50%;
    transform: translateX(-50%);
    background: #eee;
    border-radius: 5px;
    color: #555;
    padding: 5px 10px;
    border: 2px solid #555;
  }
  &::-ms-thumb:after {
    position: absolute;
    top: -35px;
    left: 50%;
    transform: translateX(-50%);
    background: #eee;
    border-radius: 5px;
    color: #555;
    padding: 5px 10px;
    border: 2px solid #555;
  }
  &::-moz-range-thumb:after {
    position: absolute;
    top: -35px;
    left: 50%;
    transform: translateX(-50%);
    background: #eee;
    border-radius: 5px;
    color: #555;
    padding: 5px 10px;
    border: 2px solid #555;
  }
}

input[type=range]:focus::-webkit-slider-runnable-track {
  background: #ccc;
}

input[type=range]:focus::-ms-track {
  background: #ccc;
}

input[type=range]:focus::-moz-range-track {
  background: #ccc;
}
```
```js
var rng = document.querySelector("input");
var add = document.getElementById("increase");
var cut = document.getElementById("decrease");

read("mousedown");
read("mousemove");

function read(evtType) {
  rng.addEventListener(evtType, function() {
    window.requestAnimationFrame(function() {
      document.querySelector("div").innerHTML = rng.value;
    });
  });
}

add.addEventListener('click', function() {
  rng.value++;
  window.requestAnimationFrame(function() {
    document.querySelector("div").innerHTML = rng.value;
  });
});

cut.addEventListener('click', function() {
  rng.value--;
  window.requestAnimationFrame(function() {
    document.querySelector("div").innerHTML = rng.value;
  });
});
```
