### ISSUE TITLE
[css] box-shadow 小創意

### ISSUE THREAD

**Issue by Shenglian** [Shenglian/WORK_TIP#41]
https://jsfiddle.net/0v23nfy3/

**Comment by Shenglian** [comment]
```scss
$grey: #7A8590 + 20;
@import url('https://fonts.googleapis.com/css?family=Arimo');
@import url('https://fonts.googleapis.com/css?family=Roboto');
body {
  background: linear-gradient(50deg, #C6D8AF 50%, #C2F8CB);
}

.container {
  position: absolute;
  left: 50%;
  top: 50%;
  transform: translate(-50%, -50%);
}

.calendar {
  width: 200px;
  height: 200px;
  box-shadow: 
    inset 0 50px 0 #CE5F5F, 
    inset 0 -3px 5px #666 + 60, 
    inset 0 200px 0 #FFF, 
    0 3px 5px #000 + 40, 
    7px 10px 0 $grey, 
    -7px 10px 0 $grey;
}

.calendar:before {
  content: '19';
  color: #000;
  position: absolute;
  top: 60px;
  left: 50px;
  font-size: 100px;
  font-family: 'Arimo', sans-serif;
  z-index: 999;
}

.calendar:after {
  position: absolute;
  content: 'JAN';
  left: 70px;
  top: 8px;
  font-size: 30px;
  font-family: 'Roboto', sans-serif;
  text-transform: uppercase;
  color: #FFF;
  letter-spacing: 3px;
}
```
