### ISSUE TITLE
[css] Grid

### ISSUE THREAD

**Issue by Shenglian** [Shenglian/WORK_TIP#44]
[Grid](https://jsfiddle.net/dL93eetc/1/)

**Comment by Shenglian** [comment]
```html
<button id="grid_2">Grid_2</button>
<button id="grid_3">Grid_3</button>
<button id="grid_4">Grid_4</button>
<button id="grid_12">Grid_12</button>
<button id="grid_row_column">Grid_Row_Column</button>
<button id="grid_template">Grid_Template</button>
<button id="remove_corner_grid_template">Remove_Corner_Grid_Template</button>

<button id="add_gap">Add Gap</button>

<div class="wrapper">
  <div class="item">h</div>
  <div class="item">m</div>
  <div class="item">c</div>
  <div class="item">f</div>
  <div class="item">z</div>
  <div class="item">p</div>
</div>
```
```scss
.wrapper {
  display: grid;
  grid-template-rows: 50px 100px 50px;
  .item {
    display: flex;
    justify-content: center;
    align-items: center;
    background-color: #333;
    font-size: 12px;
    color: #fff;
    &:nth-child(1) {
      background-color: #393E46;
    }
    &:nth-child(2) {
      background-color: #5C636E;
    }
    &:nth-child(3) {
      background-color: #F96D00;
    }
    &:nth-child(4) {
      background-color: #F2F2F2;
    }
    &:nth-child(5) {
      background-color: #38817A;
    }
    &:nth-child(6) {
      background-color: #87DFD6;
    }
  }
  &.add_gap {
    grid-gap: 5px;
  }
  &.grid_template {
    grid-template-column: repeat(12, 1fr);
    grid-template-row: 20px 30px 40px;
    grid-template-areas:
        "m m h h h h h h h h z z"
        "m m c c c c c c c c z z"
        "m m p p p p f f f f z z";
    .item:nth-child(1){ grid-area: h; }
    .item:nth-child(2){ grid-area: m; }
    .item:nth-child(3){ grid-area: c; }
    .item:nth-child(4){ grid-area: f; }
    .item:nth-child(5){ grid-area: z; }
    .item:nth-child(6){ grid-area: p; }
  }
  &.remove_corner_grid_template {
    grid-template-column: repeat(12, 1fr);
    grid-template-row: 20px 30px 40px;
    grid-template-areas:
        ". m . h h h h h h . z ."
        ". m c c c c c c c c z ."
        ". m . p p p f f f . z .";
    .item:nth-child(1){ grid-area: h; }
    .item:nth-child(2){ grid-area: m; }
    .item:nth-child(3){ grid-area: c; }
    .item:nth-child(4){ grid-area: f; }
    .item:nth-child(5){ grid-area: z; }
    .item:nth-child(6){ grid-area: p; }
  }
  &.grid_row_column {
    grid-template-columns: 50px 50px 50px;
    grid-template-rows: 50px 50px 50px;
    .item:nth-child(1) { 
     /* grid-column-start: 1; */
     /* grid-column-end: 3; */
     grid-column: 1/4; 
    }
    .item:nth-child(6) { 
      /* grid-row-start: 2; */
      /* grid-row-start: 3; */
      grid-column: 2/4;
      grid-row: 3/4;
    }
  }
  &.grid_12 {
    grid-template-columns: repeat(12, 1fr);
  }
  &.grid_4 {
    grid-template-columns: repeat(4, 1fr);
  }
  &.grid_3 {
    grid-template-columns: repeat(3, 1fr);
  }
  &.grid_2 {
    grid-template-columns: repeat(2, 1fr);
  }
}
```
```js
!(function(d) {
  const wrapper = d.querySelector('.wrapper');
  const addGap = d.querySelector('#add_gap');
	
  const grid_row_column = d.querySelector('#grid_row_column');
  const grid12 = d.querySelector('#grid_12');
  const grid4 = d.querySelector('#grid_4');
  const grid3 = d.querySelector('#grid_3');
  const grid2 = d.querySelector('#grid_2');

	remove_corner_grid_template.addEventListener('click', () => {
    wrapper.className = wrapper.className.indexOf('add_gap') > -1 ? 'wrapper add_gap' : 'wrapper';
    wrapper.classList.toggle('remove_corner_grid_template');
  }, false);
  
  grid_template.addEventListener('click', () => {
    wrapper.className = wrapper.className.indexOf('add_gap') > -1 ? 'wrapper add_gap' : 'wrapper';
    wrapper.classList.toggle('grid_template');
  }, false);
  
  grid_row_column.addEventListener('click', () => {
    wrapper.className = wrapper.className.indexOf('add_gap') > -1 ? 'wrapper add_gap' : 'wrapper';
    wrapper.classList.toggle('grid_row_column');
  }, false);
  
  grid12.addEventListener('click', () => {
    wrapper.className = wrapper.className.indexOf('add_gap') > -1 ? 'wrapper add_gap' : 'wrapper';
    wrapper.classList.toggle('grid_12');
  }, false);

  grid4.addEventListener('click', () => {
    wrapper.className = wrapper.className.indexOf('add_gap') > -1 ? 'wrapper add_gap' : 'wrapper';
    wrapper.classList.toggle('grid_4');
  }, false);

  grid3.addEventListener('click', () => {
    wrapper.className = wrapper.className.indexOf('add_gap') > -1 ? 'wrapper add_gap' : 'wrapper';
    wrapper.classList.toggle('grid_3');
  }, false);

  grid2.addEventListener('click', () => {
    wrapper.className = wrapper.className.indexOf('add_gap') > -1 ? 'wrapper add_gap' : 'wrapper';
    wrapper.classList.toggle('grid_2');
  }, false);

  addGap.addEventListener('click', () => {
    wrapper.classList.toggle('add_gap');
  }, false);


})(document)
```
