### ISSUE TITLE
[css] flex-grow/flex-basis

### ISSUE THREAD

**Issue by Shenglian** [Shenglian/WORK_TIP#47]
```html
<ul>
  <li>123</li>
  <li>456</li>
  <li>789</li>
</ul>
```
```scss
ul, li {
  margin: 0;
  padding: 0;
}

ul {
  display: flex;
  flex-wrap: wrap;
  width: 100%;
  height: 50px;
  li {
    display: flex;
    justify-content: center;
    align-items: center;
    flex: 1;  // grow/shrink/basis
    background-color: #333;
    font-size: 13px;
    color: #fff;
    &:nth-child(1) { flex-basis: 100px; background-color: #9b9b9b;}
    &:nth-child(2) { flex-basis: 200px; background-color: #4a4a4a;}
    &:nth-child(3) { flex-basis: 300px; background-color: #333333;}
  }
}
```
