### ISSUE TITLE
[小程式] 純 css 寬度縮小為 ...

### ISSUE THREAD

**Issue by Shenglian** [Shenglian/WORK_TIP#48]
[網址](https://jsfiddle.net/x8k1z8a6/2/)
```html
<div class="demo">
  <input type="checkbox" id="WidthTogglerHeader">
  <label for="WidthTogglerHeader">拖动下面容器或选择复选框</label>
  <div class="wrapper">
    <div class="overflower">
      <div class="overflower-short">我是短文字我是短文字</div>
      <div class="overflower-long">真的可以把长的文本变成短的文本</div>
    </div>
  </div>
</div>
```

```scss
body {
  height: 100vh;
  display: flex;
}

.demo {
  width: 556px;
  margin: auto;
}

.wrapper {
  overflow: hidden;
  text-align: center;
  width: 100%;
  padding: 0.5em 1em;
  border: 1px solid;
  transition: width 1.5s;
  margin-top: 10px;
}

.overflower {
  overflow: hidden;
  display: flex;
  flex-wrap: wrap;
  /* max-width: 100%; */
  height: 1.5em;
  line-height: 1.5em;
  white-space: nowrap;
  text-overflow: ellipsis;
  .overflower-short {
    overflow: hidden;
    flex-grow: 1;
    width: 0;
    text-overflow: ellipsis;
  }

  .overflower-long {
    flex-basis: 100%;
  }
}

:checked + label + .wrapper {
  width: 20% !important;
}
```
