### ISSUE TITLE
[小程式] vertical slider css 

### ISSUE THREAD

**Issue by Shenglian** [Shenglian/WORK_TIP#59]
[vertical slider css ](https://jsfiddle.net/dsdkLf15/1/)
```html
<div class="p">
  <div class="txt">一年四季的</div>

  <div class="box">
    <div class="nums">
      <div class="num">春天</div>
      <div class="num">夏天</div>
      <div class="num">秋天</div>
      <div class="num">冬天</div>
      <div class="num">春天</div>
    </div>

  </div>
  <div class="txt">賞花趣</div>

</div>
```
```css
*,
:after,
:before,
html {
  box-sizing: border-box;
}

* {
  margin: 0;
  padding: 0;
}

body {
  display: flex;
  justify-content: center;
  align-items: center;
  width: 100%;
  height: 100vh;
  text-rendering: optimizeLegibility;
    -webkit-font-smoothing: antialiased;
  font-family: Avenir,Helvetica,Arial,sans-serif;
}

.p {
  display: flex;
  justify-content: center;
  margin: auto;
}

.box,
.txt {
  height: 28px;
}

.txt {
  display: flex;
  justify-content: center;
  align-items: center;
}

.box {
  position: relative;
  margin: 0 5px;
  overflow: hidden;
  font-size: 20px;
}

.nums {
  animation: moveSlideshow ease-in-out 5s infinite;
}

.num {
  display: flex;
  justify-content: center;
  align-items: center;
}

@-webkit-keyframes moveSlideshow {
  0% {
    transform: translateY(0px);
    color: #77C7F6;
  }
  25% {
    transform: translateY(-28px);
    color: #DDAD7B;
  }
  50% {
    transform: translateY(-56px);
    color: #C02C3F;
  }
  75% {
    transform: translateY(-84px);
    color: #FCCF46;
  }
  100% {
    transform: translateY(-112px);
    color: #77C7F6;
  }
}
```
