### ISSUE TITLE
[scss] paragraph

### ISSUE THREAD

**Issue by Shenglian** [Shenglian/WORK_TIP#9]
```scss
// 計算段落用
@mixin paragraph($height,$many){
    height: $height * $many;
    line-height: $height;
    overflow: hidden;
}
```
